apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: nas-ultra
  target:
    kind: PersistentVolumeClaim
    name: wp-pv-claim
- patch: |
    - op: replace
      path: /spec/storageClassName
      value: nas-ultra
  target:
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
