apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.cluster
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: .
      index: 1
