apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-testing

resources:
- ../../base

components:
- ../../components/ingress/contour
- ../../components/storage/thin-disk

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: harbor.markalston.net/test-apps/mysql
    newName: mysql
    newTag: 8.3.0
  - name: harbor.markalston.net/test-apps/radial/busyboxplus
    newName: radial/busyboxplus
    newTag: curl
  - name: harbor.markalston.net/test-apps/wordpress
    newName: wordpress
    newTag: php8.2-apache

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: .
      index: 1
