apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.cluster
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1
