apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage-testing

resources:
- ../../base

components:
- ../../components/ingress/istio
- ../../components/storage/nas-ultra

configMapGenerator:
- name: parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: artifactory.example.com/test-apps/mysql
    newName: mysql
    newTag: 8.3.0
  - name: artifactory.example.com/test-apps/radial/busyboxplus
    newName: radial/busyboxplus
    newTag: curl
  - name: artifactory.example.com/test-apps/wordpress
    newName: wordpress
    newTag: php8.2-apache

replacements:
- source:
    kind: ConfigMap
    name: parameters
    fieldPath: data.clusterDomain
  targets:
  - select:
      kind: VirtualService
      name: wordpress
    fieldPaths:
    - spec.hosts.0
    options:
      delimiter: '.'
      index: 1
