apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
- ../../base
- namespace.yaml

commonLabels:
  app.kubernetes.io/cluster: cluster01.markalston.net

secretGenerator:
- name: wordpress-mariadb
  namespace: wordpress
  behavior: replace
  literals:
    - mariadb-password=password
    - mariadb-root-password=password
- name: wordpress
  namespace: wordpress
  behavior: replace
  literals:
    - wordpress-password=password

replacements:
- source:
    kind: HTTPProxy
    name: wordpress
    fieldPath: metadata.labels.[app.kubernetes.io/cluster]
  targets:
  - select:
      kind: HTTPProxy
      name: wordpress
    fieldPaths:
    - spec.virtualhost.fqdn
    options:
      delimiter: .
      index: 1

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/wordpress:6.4.3-debian-12-r18
  target:
    kind: Deployment
    name: wordpress
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: harbor.markalston.net/test-apps/mariadb:11.2.3-debian-12-r4
  target:
    kind: StatefulSet
    name: wordpress-mariadb

components:
- ../../components/ingress/contour
